# Generated by Django 4.0.2 on 2022-02-14 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(default='India', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
